//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SimpleDataExampl
{
    using System;
    using System.Collections.Generic;
    
    public partial class players
    {
        public int ID { get; set; }
        public int ID_team { get; set; }
        public string Surname { get; set; }
        public string Name { get; set; }
    
        public virtual team team { get; set; }
    }
}
